config/routes.rb
Rails.application.routes.draw do
  get root "discussions#show"

  resource :discussion, only: :show
  resource :message, only: :create

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  def show
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    return if message_params[:content].blank?
    render turbo_stream: turbo_stream.append(
      "discussion_messages",
      partial: "messages/message", locals: { message_content: message_params[:content], response: false }
    )
    DiscussionMessageCreatedJob.perform_async(message_params[:content])
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discussion_helper.rb
module DiscussionHelper
  def prompt_stamp
    "#{Time.now.strftime("%H:%M:%S")}>"
  end
end

app/views/discussions/_message_form.html.slim
= form_tag message_path, class: "message-form",
  data: { controller: "message-form", action: "turbo:submit-end->message-form#resetInput" } do

  = label_tag "message[content]", ">"
  = text_field_tag "message[content]", nil, class: "message-input"

  = submit_tag "Send", class: "message-submit"

app/views/discussions/show.html.slim
nav.discussion-nav
  .discussion-title
    |> DiscussionAI
    span.discussion-subtitle powered by OpenAI

.discussion-container
  = turbo_stream_from "discussion_messages"
  #discussion_messages.messages-contaienr
    p.message-response
      = "#{prompt_stamp} Hello nice handsome human person."
      br/
      ' What can I do for you today?

  = render partial: "message_form"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiscussionAi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="discussion-app">
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.slim
p class="message-#{response ? "response" : "block"}"
  = "#{prompt_stamp} #{message_content}"